language: ruby
cache: bundler

rvm:
- 2.4.0

# before_script:
# - chmod +x ./.ci/cibuild
# 
# script: ./.ci/cibuild
# install: gem install jekyll html-proofer
# 
# The `install` step will run `bundle install` by default.
# install: bundle install

# script: jekyll build && htmlproofer ./_site --disable-external
script: bundle exec jekyll build --config _config-travis.yml && bundle exec htmlproofer --assume-extension --disable-external ./_site

# branch whitelist for GitHub Pages
branches:
  only:
  - master       # test if Pages is configured to use master
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
